### ISSUE TITLE
关于Cocos Creator 2.2版本的skew支持问题

### ISSUE THREAD

**Issue by wildfire810** [fairygui/FairyGUI-Editor#11]
不好意思，又来打扰了。

https://www.cocos.com/5707
如上面的发布说明所示

2.2.0 版本暂时不支持节点的 Skew 效果，我们会在后续提供文档引导大家手动开启 Skew 的支持。新项目建议直接使用 3D Sprite 而不是 Skew。旧项目可以先参考 [#5564] 和 [#1889] 对 js 和原生引擎进行适配，即可支持 Skew。

请问我们的版本是否使用的 3D Sprite呢？还是说我作为用户应该手工给引擎打补丁，来兼容Skew的属性？

**Comment by xiaoguzhu** [comment]
暂时没有研究这一块，所有我也无法做出决定。你可能要自己先改改试试。
