### ISSUE TITLE
【BUG】关于滚动条的固定滑块大小失效问题

### ISSUE THREAD

**Issue by sonicdjgh** [fairygui/FairyGUI-Editor#12]
在进入到滚动条的编译模式后，我勾选了“固定的滚动滑块大小”这一选项。

但是当我给我的列表的“溢出处理”的详细设置里添加该滚动条后，运行，发现无论是编辑模式还是在运行模式下，滑块的大小还是那种默认效果（即随着列表的内容长短自动适配滑块的大小）。

另外，当我重启FairyGUI Editor后，我滚动滑块的“固定的滚动滑块大小”这一选项竟然是未选中状态。

请开发者查一下这个是怎么回事，如果是bug希望尽快修复。

**Comment by xiaoguzhu** [comment]
请报告编辑器版本。

**Comment by sonicdjgh** [comment]
5.0.3版本

guzhu <notifications@github.com> 于2019年11月1日周五 下午4:27写道：

**Comment by sonicdjgh** [comment]
开发者您好，我这边又发现了相关的新问题：

[image: TIM截图20191103131449.png]
如上图所示，是将FariyGUI的一个组件发布后在Unity上使用，发现滚动滑块的最终效果是固定大小的，与我的需求一致，但是滚动条的长度以及滑动的距离是不对的；

[image: TIM截图20191103131604.png]

如上图所示，这是在FairyGUI编辑器中的运行效果，滚动条长度、滑动距离是ok的，但是滑块不是固定大小的。

FairyGUI-Editor 版本： 5.0.3

Unity版本：2019.1.4f1

望开发者尽快解决，感谢！

邓杰 <sonicdj1987@gmail.com> 于2019年11月3日周日 下午12:37写道：

**Comment by xiaoguzhu** [comment]
编辑器确实没有成功设置和保存这个属性，我重新传了一下5.0.3，已经修正了这个问题。如果你已经更新到了5.0.3，需要重新下载一下。

**Comment by sonicdjgh** [comment]
好的，十分感谢，得空我试一下，感谢大大辛勤维护。
