### ISSUE TITLE
Vbox / Hbox / Flexbox layouts

### ISSUE THREAD

**Issue by jimon** [fairygui/FairyGUI-Editor#14]
While current layout via relations is ok for simple layouts, it feels way too barebone and simple.

Would be nice to have elements or faster way to achieve vertical box / horizontal box layout between selected elements.

Also having something like flexbox (not necessarily grid layout, but the rest of it, like proportional stretching) seems like would simplify things a bit :)

**Comment by xiaoguzhu** [comment]
Use advance group, it has horizontal layout and vertical layout

**Comment by jimon** [comment]
Ok, completely missed layout combobox there :) With "Scale only specified index element" it does solve my current problem. Though the system is not as flexible as flexbox, I guess it is sufficient for game ui. Thanks!
