### ISSUE TITLE
Edit Path button only works when first key frame of timeline is selected

### ISSUE THREAD

**Issue by jimon** [fairygui/FairyGUI-Editor#15]
![image](https://user-images.githubusercontent.com/1333661/75631820-71f22b00-5bf6-11ea-88fc-360ea64078ee.png)

So I have made a timeline with 1) two key frames 2) tween in between.
I've selected both key frames and enabled "Use Path"

Now when I select the component, the path is only visible if I click "Edit Path" when first frame is selected. If I move timeline to second frame - path disappears.

Version 5.0.10

**Comment by xiaoguzhu** [comment]
I try to reproduce. First I select a keyframe which has 'Use Path' enabled, then I move timeline to second frame. I can see the path is still visible.

**Comment by jimon** [comment]
Hm, after playing a bit, I think it's not broken but more confusing. Because:
When I have two key frames ( start and end ) I can click "Use Path" on first and second, but having use path / tween on second one doesn't make much sense as there are no keyframes after that. So path is not rendered when clicking edit path on second keyframe, but works on first one.
