### ISSUE TITLE
classinfo.classname跟组件名前缀绑定一起，不太灵活

### ISSUE THREAD

**Issue by shelllee** [fairygui/FairyGUI-Editor#23]
### 问题抛出
- classinfo.classname跟组件名前缀绑定一起，不太灵活，比如：
    1. 新建包并命名为: `common`
    2. 设置组件名前缀: `UI`
    3. 然后导出，发现代码中class名为`UIcommon`，而不是期望的`UICommon`

### 涉及
- 目前发现涉及到的地方
    1. 类名前缀
    2. 成员前缀

### 期望修改
- 虽然能在导出插件脚本中获取setting，再去根据前缀进行魔改，但感觉多此一举，能完全由导出插件自己拼接就好了

**Comment by xiaoguzhu** [comment]
因为个人需求不一致，还是需要在插件里自定义的
