### ISSUE TITLE
Command-line publishing doesn't work in  version 2020.3.3?

### ISSUE THREAD

**Issue by jgod** [fairygui/FairyGUI-Editor#24]
[Command-line publishing](https://en.fairygui.com/docs/guide/editor/publish.html#Command-line-publishing) stopped working for version 2020.3.3. It used to work on my previous version (5.0.7).

I am using this command:

```
 "C:/tools/FairyGUI-Editor_2020.3.3/FairyGUI-Editor.exe" -p "C:\Users\Justin\Desktop\MyGame\_proj-fairygui\MyGameUI.fairy" -o "C:\Users\Justin\Desktop\MyGame\cc-proj\assets\resources\FairyGUI"
```

**Comment by xiaoguzhu** [comment]
Hi, syntax was changed. please check [https://en.fairygui.com/docs/guide/editor/publish.html#Command%20line%20publishing](https://en.fairygui.com/docs/guide/editor/publish.html#Command%20line%20publishing)

**Comment by jgod** [comment]
Thank you for the quick response.
Ah, I see that you need `-batchmode` now.
