### ISSUE TITLE
BUG: 高级组的scale属性控制预览和实际表现不一致。以及此问题衍生的恶性bug

### ISSUE THREAD

**Issue by fy0** [fairygui/FairyGUI-Editor#26]
先简单说明一下背景，我在做一个列表。要实现一个效果就是当前选中的项要放大，不选中了缩回去。

我选择使用控制器和属性控制来实现这个效果，实现过程中发现这样一个问题，我用一个最小实现来描述：

#### 创建对象

![image](https://user-images.githubusercontent.com/1579850/106410908-e8d71a00-647e-11eb-85de-7c892676132f.png)

n0: 白
item: 蓝父级，高级组
n1: 蓝

#### 对item设定控制

![image](https://user-images.githubusercontent.com/1579850/106411009-10c67d80-647f-11eb-85a8-2d7c11c2ad62.png)

![image](https://user-images.githubusercontent.com/1579850/106411019-1623c800-647f-11eb-8ec6-e72f9daa3e4a.png)

如编辑器所见，**n1的大小随着item的大小改变而改变**，这个操作其实违反了FGUI的布局约束。

我们看下预览：

focus 0
![image](https://user-images.githubusercontent.com/1579850/106411213-a530e000-647f-11eb-9a98-a9c80f3cb3e5.png)

focus 1
![image](https://user-images.githubusercontent.com/1579850/106411220-acf08480-647f-11eb-84e2-d125c900d30a.png)

实际预览中，n1的大小丝毫未变，这是符合逻辑的。

接下来就是衍生恶性BUG的演示。

#### 建立关联

![image](https://user-images.githubusercontent.com/1579850/106411376-20929180-6480-11eb-9ee9-0ef3a805a9ab.png)

现在在测试模式效果如我们一开始所想：

![image](https://user-images.githubusercontent.com/1579850/106411397-2f794400-6480-11eb-923c-db49dad5aaf6.png)

![image](https://user-images.githubusercontent.com/1579850/106411409-36a05200-6480-11eb-98fb-25bced1b9a2c.png)

#### 问题所在

但是在编辑模式随便切几次状态就会出事

![image](https://user-images.githubusercontent.com/1579850/106411457-546db700-6480-11eb-90db-eb3f417d1346.png)

切1，明显变大，再切回去，变小

![image](https://user-images.githubusercontent.com/1579850/106411486-5fc0e280-6480-11eb-8573-5fce4b2f608f.png)

迭代几次就会大的更大，小的为0了。

ctrl+z也不能恢复，唯一办法只有关闭文件且不保存，同时祈祷上一个保存的版本没受到影响。

**Comment by fy0** [comment]
最后一步的组件：

```xml
<?xml version="1.0" encoding="utf-8"?>
<component size="250,250">
  <controller name="focus" pages="0,,1," selected="0"/>
  <displayList>
    <graph id="n0_l48x" name="n0" xy="0,0" size="250,250" type="rect"/>
    <graph id="n1_l48x" name="n1" xy="0,0" size="200,200" group="n2_l48x" type="rect" fillColor="#ff0033ff">
      <relation target="n2_l48x" sidePair="width-width,height-height"/>
    </graph>
    <group id="n2_l48x" name="item" xy="0,0" size="200,200" advanced="true">
      <gearXY controller="focus" pages="1" values="25,25" default="0,0"/>
      <gearSize controller="focus" pages="0,1" values="200,200,1,1|250,250,1,1"/>
    </group>
  </displayList>
</component>
```

**Comment by xiaoguzhu** [comment]
先阅读教程 组。

**Comment by fy0** [comment]
> 先阅读教程 组。

你要的教程：
```
普通组的作用有：

当组大小改变时，组内的内容将同时增大或者缩小。

高级组：
高级组除了具有普通组所有的功能外，……
```


那我问你：

* “当组大小改变时，组内的内容将同时增大或者缩小”有无问题？

**Comment by xiaoguzhu** [comment]
再看清楚普通组是什么。

**Comment by fy0** [comment]
@xiaoguzhu 

例子是高级组
