### ISSUE TITLE
Component with decimal scaled value won't render at Test | Runtime

### ISSUE THREAD

**Issue by Armitage1982** [fairygui/FairyGUI-Editor#29]
If any component is set with a decimal Scale value (like 0,5 or 1,5) then it will not be rendered in Test view (F5) nor inside the Unity Runtime. 
Related problem https://github.com/fairygui/FairyGUI-Editor/issues/30#issue-1323008026

**Comment by Armitage1982** [comment]
I confirm that changing the format of the region to "English (Europe)" solved the problem in my case.
Changing manually the punctuation symbol for the decimal is not enough
![image](https://user-images.githubusercontent.com/5075666/181916205-95bb5ecb-512c-441b-8227-e0c0ef63cc17.png)

**Comment by xiaoguzhu** [comment]
Will fix this issue in Editor 6.0.0 which will release soon.

**Comment by xiaoguzhu** [comment]
fixed
