### ISSUE TITLE
Linux builds

### ISSUE THREAD

**Issue by Matan** [fairygui/FairyGUI-Editor#3]
Hi, I'm really keen to start using this. Would it be possible to supply Linux builds of the editor alongside Windows and OSX?

Thanks!

**Comment by fairygui** [comment]
It's pity that Linux version is not available.

**Comment by Matan** [comment]
It is a pity indeed, do you plan on running a build for linux in the future?

**Comment by fairygui** [comment]
I'll try if have time, however, the possibility is slim.

**Comment by CrandellWS** [comment]
It runs with https://github.com/wine-mirror/wine just fine

**Comment by CrandellWS** [comment]
![image](https://user-images.githubusercontent.com/5300522/50957537-73114780-148c-11e9-8186-ac7db7f1eb95.png)

**Comment by CrandellWS** [comment]
ty

**Comment by delaneyj** [comment]
This no longer appears to be the case.  Since this is built with Unity could we get a native linux build?
