### ISSUE TITLE
编辑器在mac 使用带有regular 类型的字体无效

### ISSUE THREAD

**Issue by codeMonkeyWang** [fairygui/FairyGUI-Editor#4]
经测试，字体功能在win下是可以正常使用的，在mac下带有regular类型的字体都无法使用。
这个问题影响还挺大的，希望能尽快解决

**Comment by fairygui** [comment]
无法使用是什么意思？

**Comment by codeMonkeyWang** [comment]
字体会变成默认字体，设置的自定义字体无效。

**Comment by fairygui** [comment]
具体是指哪个字体，我这里测试没有问题

**Comment by codeMonkeyWang** [comment]
有大量的字体都是默认字体，不知道什么情况。我用其它设计软件，这些字体是可以起作用的。
![1517415761594](https://user-images.githubusercontent.com/3906539/35634295-4eaf2fba-06e6-11e8-9509-2d17f6bb9dfd.jpg)
好像跟是不是regular 类型 也没关系

**Comment by xiaoguzhu** [comment]
对于部分字体，编辑器能识别的字体名称不一定是字体的中文名称。查看准确的系统字体名称，你可以下载FontCreator软件，查看字体的Font Family属性。

**Comment by xiaoguzhu** [comment]
已解决，请使用最新编辑器版本。
