### ISSUE TITLE
编辑器内字体描边效果不准确

### ISSUE THREAD

**Issue by zeas2** [fairygui/FairyGUI-Editor#6]
假设描边设置为3像素，在编辑器内无论如何缩放，描边始终是3个像素而非伴随缩放而增减。
另外描边貌似是字体复制两个副本，上色后分别向左上和右下偏移实现的，在描边的值较大时左下和右下看起来有缺口。
既然字体的粗体开关是有效的，那为何不使用TTF的outline特性来实现描边呢？

**Comment by xiaoguzhu** [comment]
描边的缩放，是一个问题，但目前解决不了，只能作为一个已知缺陷。
描边的实现，无论是编辑器的引擎还是Unity引擎，都没有提供，所以只能通过这种方式实现。你所说的TTF的outline特性，我不掌握，如果要直接操作TTF来渲染字体，这未免太底层，当然不是不可能，只是实现难度太大。

**Comment by HellGame** [comment]
可以参考TextMesh Pro的描边呀，那个效果很好。

**Comment by xiaoguzhu** [comment]
TextMesh Pro和这里说的不是一回事，它是预生成的。

**Comment by HellGame** [comment]
刚搜到了篇文章是解决描边问题的 http://gad.qq.com/article/detail/29266 但没有完整的代码

**Comment by xiaoguzhu** [comment]
以前看过。我不觉得它是“解决”描边问题的，它只是解决一个特定的显示需要。
