### ISSUE TITLE
在编辑动效时预览动效，控件的初始状态不正确

### ISSUE THREAD

**Issue by zeas2** [fairygui/FairyGUI-Editor#7]
[test.zip](https://github.com/fairygui/FairyGUI-Editor/files/2170352/test.zip)
比如这个工程，控件设置为不可见，在普通编辑模式下预览效果是正确的。
如果进入动效编辑状态，再预览时控件的初始不可见状态就无效了。
同样受影响的还有透明度属性。

**Comment by xiaoguzhu** [comment]
是有这个问题，主要是由于勾选了自动播放引起的。下个版本发布时修正。
