### ISSUE TITLE
导出的二进制格式，关联模式 左->左% 的百分比没有生效

### ISSUE THREAD

**Issue by zeas2** [fairygui/FairyGUI-Editor#8]
观察过导出的二进制数据，在描述RelationType的字节后面有个字节对应百分比，但没有输出成1
目前就发现Left_Left有问题，Width和Height的百分比输出正确，其它的情况还没测试

**Comment by xiaoguzhu** [comment]
问题存在，将在下一个小版本修复。谢谢反馈。
